### ISSUE TITLE
Pre-Master key only 113 byte long

### ISSUE THREAD

**Issue by xanpj** [Tim---/drown#1]
Hi Tim,

awesome work! We have a research project going on here and are trying to user your codebase.
Two question:
- The Pre-Master Secret key we get from the oracle is 113 byte long. Does it conform with the secret part format of the PMS somehow?
- How can we decrypt the SSL connections in wireshark, when we only collect the TCP connections. There is know way of importing the pre master log file for this.

Thanks in advance!
Alex

**Comment by Tim---** [comment]
Hi,

Just to clarify, the output of ./decrypt is the input format used by Wireshark to decrypt SSL connections.
So it should look like this :

`RSA 3043f623bd2bd09a 03030f7e7cea2527128f6ede35f96de0c0aed0a9d668d0499fe1db253f670694155eb89c8f2dc64ef3fb507832af1a36`

The first hex number corresponds to the first 8 bytes of the EPMS, and the second is the decoded PMS of 48 bytes (see https://tools.ietf.org/html/rfc5246#page-58). We can see that PMS looks fine since it starts with 03 03, which indicates the use of TLS 1.2.

For your second question, I'm not sure I understand but I assume you mean that your SSL traffic is not recognized by Wireshark because you are using an unusual port. In this case you can right click on one of the packets and choose 'Decode As...'. You can then assign port 4433 to SSL. After that, Wireshark will recognize the packets as SSL, and you should be able to decode the traffic.

Cheers,
Tim.
